version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: match_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  db-volume:
